### PR TITLE
 allow for restoring clusterdeployment and clusterprovision

### PR DESCRIPTION
**Pull request by staebler**
* The installed field in clusterdeployment has been moved from the status to the spec. This allows the field to be retained when a clusterdeployment is restored. The installed field in status is deprecated but will be retained until all existing clusterdeployments are converted to use the installed field in spec.

* Adjust the validation for clusterprovision to accommodate adopting an existing cluster. When adopting, the expectation is that the podSpec field will be omitted. So when the podSpec field is empty, the validation ensures that the stage is "complete", that the attempt number if 0, and that there is not a previous infra ID or cluster ID.

* If the clusterdeployment is marked as installed but there is not a reference to the clusterprovision, then the controller will attempt to adopt an existing completed clusterprovision. Upon adoption, the infra ID, cluster ID, admin kubeconfig secret, and admin password secret will be copied from the clusterprovision to the clusterdeployment.

### CODE REVIEW

**Comment by dgoodwin** [comment]
This is failing a suspicious number of times, but I found this in the hive-controllers log so it's still looking flaky.

```
time="2019-09-05T14:59:03Z" level=info msg="install job failed" controller=clusterProvision job=hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6-provision name=cluster-test/hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6
time="2019-09-05T14:59:03Z" level=info msg="processing new install log" controller=clusterProvision job=hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6-provision name=cluster-test/hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6
time="2019-09-05T14:59:03Z" level=info msg="install log line" controller=clusterProvision job=hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6-provision line="level=info msg=\"Consuming \\\"Worker Ignition Config\\\" from target directory\"" name=cluster-test/hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6
time="2019-09-05T14:59:03Z" level=info msg="install log line" controller=clusterProvision job=hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6-provision line="level=info msg=\"Consuming \\\"Master Ignition Config\\\" from target directory\"" name=cluster-test/hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6
time="2019-09-05T14:59:03Z" level=info msg="install log line" controller=clusterProvision job=hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6-provision line="level=info msg=\"Consuming \\\"Bootstrap Ignition Config\\\" from target directory\"" name=cluster-test/hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6
time="2019-09-05T14:59:03Z" level=info msg="install log line" controller=clusterProvision job=hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6-provision line="level=info msg=\"Creating infrastructure resources...\"" name=cluster-test/hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6
time="2019-09-05T14:59:03Z" level=info msg="install log line" controller=clusterProvision job=hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6-provision line="level=error" name=cluster-test/hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6
time="2019-09-05T14:59:03Z" level=info msg="install log line" controller=clusterProvision job=hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6-provision line="level=error msg=\"Error: Error applying plan:\"" name=cluster-test/hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6
time="2019-09-05T14:59:03Z" level=info msg="install log line" controller=clusterProvision job=hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6-provision line="level=error" name=cluster-test/hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6
time="2019-09-05T14:59:03Z" level=info msg="install log line" controller=clusterProvision job=hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6-provision line="level=error msg=\"1 error occurred:\"" name=cluster-test/hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6
time="2019-09-05T14:59:03Z" level=info msg="install log line" controller=clusterProvision job=hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6-provision line="level=error msg=\"\\t* module.vpc.aws_lb.api_internal: 1 error occurred:\"" name=cluster-test/hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6
time="2019-09-05T14:59:03Z" level=info msg="install log line" controller=clusterProvision job=hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6-provision line="level=error msg=\"\\t* aws_lb.api_internal: timeout while waiting for state to become 'active' (last state: 'provisioning', timeout: 10m0s)\"" name=cluster-test/hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6
time="2019-09-05T14:59:03Z" level=info msg="install log line" controller=clusterProvision job=hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6-provision line="level=error" name=cluster-test/hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6
time="2019-09-05T14:59:03Z" level=info msg="install log line" controller=clusterProvision job=hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6-provision line="level=error" name=cluster-test/hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6
time="2019-09-05T14:59:03Z" level=info msg="install log line" controller=clusterProvision job=hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6-provision line="level=error" name=cluster-test/hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6
time="2019-09-05T14:59:03Z" level=info msg="install log line" controller=clusterProvision job=hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6-provision line="level=error" name=cluster-test/hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6
time="2019-09-05T14:59:03Z" level=info msg="install log line" controller=clusterProvision job=hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6-provision line="level=error" name=cluster-test/hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6
time="2019-09-05T14:59:03Z" level=info msg="install log line" controller=clusterProvision job=hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6-provision line="level=error msg=\"Terraform does not automatically rollback in the face of errors.\"" name=cluster-test/hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6
time="2019-09-05T14:59:03Z" level=info msg="install log line" controller=clusterProvision job=hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6-provision line="level=error msg=\"Instead, your Terraform state file has been partially updated with\"" name=cluster-test/hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6
time="2019-09-05T14:59:03Z" level=info msg="install log line" controller=clusterProvision job=hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6-provision line="level=error msg=\"any resources that successfully completed. Please address the error\"" name=cluster-test/hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6
time="2019-09-05T14:59:03Z" level=info msg="install log line" controller=clusterProvision job=hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6-provision line="level=error msg=\"above and apply again to incrementally change your infrastructure.\"" name=cluster-test/hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6
time="2019-09-05T14:59:03Z" level=info msg="install log line" controller=clusterProvision job=hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6-provision line="level=error" name=cluster-test/hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6
time="2019-09-05T14:59:03Z" level=info msg="install log line" controller=clusterProvision job=hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6-provision line="level=error" name=cluster-test/hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6
time="2019-09-05T14:59:03Z" level=info msg="install log line" controller=clusterProvision job=hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6-provision line="level=fatal msg=\"failed to fetch Cluster: failed to generate asset \\\"Cluster\\\": failed to create cluster: failed to apply using Terraform\"" name=cluster-test/hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6
time="2019-09-05T14:59:03Z" level=info msg="install log line" controller=clusterProvision job=hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6-provision line= name=cluster-test/hive-549be609-cc56-4aa8-8f05-875094a13bb4-0-9qcg6
```

**Comment by staebler** [comment]
Ah, I think that the e2e test is expecting to find `.status.installed` set to true instead of `spec.installed`.

**Comment by staebler** [comment]
14728722...a0dffe02
* Fixed e2e post-install tests to use `.spec.installed` to determine whether a clusterdeployment has been installed.

**Comment by staebler** [comment]
a0dffe02...3d0be5f0
* Update clusterdeployment validation to allow `spec.installed` to be updated from `false` to `true`.

**Pull request merged**
