### PR TITLE
Add ClusterPool API and controller.

### PR DESCRIPTION
**Pull request by staebler**
Allows defining a pool of clusters of a certain size to be kept ready for use. Uses the builder we use for hiveutil create-cluster to generate all artifacts, including an install-config. As such options for customization are a bit restricted, but should be helpful for anyone looking to keep clusters up and running.

Future work will allow clusters to be claimed by users, and immediately hibernating clusters as soon as they're ready and waking them up when claimed.

### CODE REVIEW

**Comment by staebler** [comment]
This builds on the work started in https://github.com/openshift/hive/pull/1037.

**Comment by staebler** [comment]
Resolves #847.

**Comment by dgoodwin** [comment]
I've gone through each commit and everything looks good, but the reap namespace commit appears to be both in this PR and #1057 with a different SHA, can you advise what you'd like to do there? Feels like it should be dropped here and we merge it over in #1057.

**Comment by dgoodwin** [comment]
Maybe the diff sha is just how git works if it's applied on another branch, if they are identical we can merge it all here.

**Comment by staebler** [comment]
> I've gone through each commit and everything looks good, but the reap namespace commit appears to be both in this PR and #1057 with a different SHA, can you advise what you'd like to do there? Feels like it should be dropped here and we merge it over in #1057.

I created the reap namespaces PR first. Then, after doing more ClusterPool work, I added it to this PR. I don't care whether we merge the reap namespaces PR first or not. If it does go in first, then I will rebase this PR to exclude the reap namespaces work.

**Pull request merged**
