### PR TITLE
HiveConfig.Spec.DeploymentConfig: customize controller resources

### PR DESCRIPTION
**Pull request by 2uasimojo**
Heretofore, container resource requests for the deployments/statefulSets managed by hive-operator were hardcoded into the operator's bindata, with no way to customize them.

This commit adds a new field to HiveConfig.Spec called DeploymentConfig. In it, you may list a subsection for each of the
deployments/statefulSets (hive-controllers, hive-clustersync, and/or hiveadmission) containing a `resources`, which is a standard corev1.ResourceRequirements. For example:

```yaml
  deploymentConfig:
  - deploymentName: hive-controllers
    resources:
      requests:
        memory: 256Mi
  - deploymentName: hive-clustersync
    resources:
      requests:
        cpu: 30m
        memory: 257Mi
```

hive-operator will redeploy the controllers (per usual when HiveConfig is edited), copying the specified `resources` into the container spec for the named deployment/statefulSet.

Note that this is separate from, and unrelated to, HiveConfig.Spec.ControllersConfig, which tailors the behavior of specific controllers running within the containers.

[HIVE-2091](https://issues.redhat.com//browse/HIVE-2091)

### CODE REVIEW

**Comment by 2uasimojo** [comment]
Hm, is it worth tweaking the docs for this?

**Comment by hongkailiu** [comment]
> Hm, is it worth tweaking the docs for this?

Thanks for the quick action. @2uasimojo 
It is clear to me how to use the new fields in `HiveConfig`.
I can also imagine that doc would be useful for the users without seeing this PR.

Ideally, no docs like this are needed if oc-explain works on the api. But it seems not working

```console
oc explain hiveConfig
KIND:     HiveConfig
VERSION:  hive.openshift.io/v1

DESCRIPTION:
     <empty>
```

I thought it might be the result of the api coming from Hive, not an out-of-box application. But i found it works for `Issuer` which comes from Cert-Manager, also a third-party application.

```
oc explain issuers
KIND:     Issuer
VERSION:  cert-manager.io/v1

DESCRIPTION:
     An Issuer represents a certificate issuing authority which can be
     ...
...
```

**Comment by 2uasimojo** [comment]
@hongkailiu This is what I was asking: is `oc explain` adequate or is it worth calling out some aspect of this feature in the docs, e.g. [scaling](https://github.com/openshift/hive/blob/master/docs/scaling-hive.md); or in using-hive, where we have [this section](https://github.com/openshift/hive/blob/master/docs/using-hive.md#scaling-clustersync) about scaling clustersync horizontally by increasing controller replicas. @abutcher thoughts?

As for your `oc explain` not working...
- Historically this has been due to a misconfiguration of the CRD itself; but we've fixed that problem (a couple times IIRC) in the past.
- At least on CI's `hive-rj7rg` cluster, `oc explain` is working for me.

Can you please tell me what cluster you're looking at, and dump the status conditions from `oc get crd hiveconfigs.hive.openshift.io -o yaml`? (Let's do this offline, since it's likely to be an unrelated issue.)

**Comment by abutcher** [comment]
@2uasimojo I'm in favor of adding a small section about this config option to using-hive.

**Review by abutcher — APPROVED** [review]
Implementation is clean and looks good to me! Waiting to stamp in case we want to include an update about the hiveconfig field to the "using-hive" doc.

**Comment by 2uasimojo** [comment]
@abutcher how 'bout I do that in a fup to save on CI resources? (This should merge without retesting, and the fup should skip all the tests if it's just a doc update.)

**Comment by 2uasimojo** [comment]
docs: https://github.com/openshift/hive/pull/1944

**Pull request merged**
