### PR TITLE
Updated makefile by adding .PHONY for make target

### PR DESCRIPTION
**Pull request by gyliu513**
/cc @dgoodwin

### CODE REVIEW

**Comment by gregsheremeta** [comment]
> Updated makefile for hive

@gyliu513 Please be more descriptive -- updated it *to do what*?

**Comment by gyliu513** [comment]
@gregsheremeta Done, thanks!

**Comment by dgoodwin** [comment]
I don't even know what these do but it looks like they were missing on those targets. :)

/lgtm

/ok-to-test

**Comment by gyliu513** [comment]
@dgoodwin please refer to https://stackoverflow.com/questions/2145590/what-is-the-purpose-of-phony-in-a-makefile for some explanation :-)

**Comment by dgoodwin** [comment]
Today I learned! Thanks. :)

**Pull request merged**
