### PR TITLE
bump(github.com/openshift/installer) - 63c63a0015f8f7cd894a93c0a6c0d6565ee8d05a

### PR DESCRIPTION
**Pull request by csrwng**

### CODE REVIEW

**Comment by dgoodwin** [comment]
/lgtm

Massive thanks for getting that.

**Comment by csrwng** [comment]
So this is now working locally, with lots of caveats. Go needs to be bumped to 1.12, and changes are needed in the installer to decouple things. For now, I'm using my own fork of the installer.

**Comment by csrwng** [comment]
@dgoodwin this should be ready for review. The fix to the installer and switch to go 1.12 have already happened, so build/test is looking good.

**Comment by csrwng** [comment]
Seems like a CI infra issue:
```
            "message": "Failed to pull image \"registry.svc.ci.openshift.org/ci-op-hjnz3g39/stable:hive\": rpc error: code = Unknown desc = Error reading blob sha256:44de5d7fba4bbe79c0b872aed71e529429fa9930b45b2272f3ddc22d645ae590: Invalid status code returned when fetching blob 503 (Service Unavailable)",
```
/retest

**Comment by dgoodwin** [comment]
Seems stuck....

**Pull request merged**
