### PR TITLE
Specify the `kind` for the RoleBinding reference fixes #835

### LINKED ISSUE #835: Attempt to deploy Hive v1alpha on OpenShift 4.3 failed
## What I did
```
# sourced my KUBECONFIG
git clone https://github.com/openshift/hive 
git checkout v1
cd hive
DEPLOY_IMAGE=quay.io/rhibmcollab/hive:v1-alpha-latest make deploy
```

## What happened
Deployment failed with error message:
```
The RoleBinding "hiveapi" is invalid: roleRef.kind: Unsupported value: "": supported values: "Role", "ClusterRole"
make: *** [deploy] Error 1
```

## What I expected:

Successful deployment and operational Hive controllers.

### PR DESCRIPTION
**Pull request by mdelder**

### CODE REVIEW

**Comment by gregsheremeta** [comment]
can you retarget to master? v1 is closed / will soon be deleted. thanks :)

**Comment by staebler** [comment]
This is obsolete in the master branch.

**Comment by gregsheremeta** [comment]
thanks @staebler

**Comment by mdelder** [comment]
This may no longer be required as the change that I made in `v1` was already in `master`.

**Pull request closed without merging**
