### PR TITLE
Fix missed ArgoCD config deepcopy.

### PR DESCRIPTION
**Pull request by dgoodwin**
Not sure how this was missed, seems like something verify should have caught.

I've got this from running make update and make vendor, after removing _output dir to let it fetch latest controller gen.

/assign @abutcher 
/cc @2uasimojo

### CODE REVIEW

**Comment by 2uasimojo** [comment]
Okay, this looks sane and right -- but I can't reproduce, which means something is wrong with the tooling. We don't need to hold up this PR, but I want to get to the bottom of it.

**Comment by 2uasimojo** [comment]
FWIW, controller-gen isn't involved in this flow, so it's not that. And the script we're using is coming from vendor/ and installs deepcopy-gen etc. from *itself*, so there shouldn't be a possibility of a version mismatch there.

What's most worrying that CI isn't failing *before or after* your change.

**Comment by 2uasimojo** [comment]
@dgoodwin now that #1450 merged, you should be able to rebase this and it'll go back to just the deepcopy deltas.

**Comment by dgoodwin** [comment]
Pushed.

**Comment by 2uasimojo** [comment]
I suspect (but don't feel like trying to prove) that this would have been caught via #1676.

**Pull request merged**
