### PR TITLE
MachinePool: Add GCP SecureBoot

### PR DESCRIPTION
**Pull request by 2uasimojo**
[HIVE-2261](https://issues.redhat.com//browse/HIVE-2261)

### CODE REVIEW

**Comment by renan-campos** [comment]
That was fast! From my naive reading of this, I believe this does exactly what we need.

**Review by renan-campos — APPROVED** [review]

**Comment by 2uasimojo** [comment]
Wait, why did this merge? Because e2e-gcp is optional?

We need to make sure this test passes...

**Comment by 2uasimojo** [comment]
looking at the result from this PR, it smells like it was probably just a flake

**Comment by suhanime** [comment]
>Wait, why did this merge? Because e2e-gcp is optional?

Maybe because of [this](https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/hive/openshift-hive-master-presubmits.yaml#L240)?

**Comment by 2uasimojo** [comment]
> > Wait, why did this merge? Because e2e-gcp is optional?
> 
> Maybe because of [this](https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/hive/openshift-hive-master-presubmits.yaml#L240)?

That's why it ran; [this](https://github.com/openshift/release/blob/master/ci-operator/jobs/openshift/hive/openshift-hive-master-presubmits.yaml#L238) is why it didn't block merge. Makes sense as configured I guess... but I wonder if there's a "required iff run by `run_if_changed` rule" mode? [Asking](https://redhat-internal.slack.com/archives/CBN38N3MW/p1696889627522809)...

**Comment by 2uasimojo** [comment]
For those following along at home, made the jobs non-optional via https://github.com/openshift/release/pull/44171, testing via https://github.com/openshift/hive/pull/2129.

**Comment by 2uasimojo** [comment]
#2128 passed, so we're good here.

#2129 worked (i.e. didn't merge) so we've closed the gap with the not-run-by-default e2es.

**Pull request merged**
