### PR TITLE
Cleanup use of mismatched images and clarify docs.

### PR DESCRIPTION
**Pull request by dgoodwin**
Our template was defaulting to using latest installer/hive, but an older
pinned release image which is not compatible.

### CODE REVIEW

**Comment by dgoodwin** [comment]
/hold 

temporarily using the older images for CI, will unhold once that installer bug is fixed.

**Comment by dgoodwin** [comment]
@twiest can you take another look.

**Comment by csrwng** [comment]
Vpc limit exceeded. Hopefully it's temporary
/retest

**Pull request merged**
