### PR TITLE
merge v1 into master

### PR DESCRIPTION
**Pull request by staebler**
/hold

### CODE REVIEW

**Comment by csrwng** [comment]
```
hack/verify-generated.sh
make[1]: Entering directory `/go/src/github.com/openshift/hive'
go generate ./pkg/... ./cmd/...
pkg/awsclient/client.go:51: running "mockgen": exec: "mockgen": executable file not found in $PATH
pkg/controller/dnsendpoint/nameserver/query.go:7: running "mockgen": exec: "mockgen": executable file not found in $PATH
pkg/controller/remotemachineset/actuator.go:11: running "mockgen": exec: "mockgen": executable file not found in $PATH
pkg/gcpclient/client.go:19: running "mockgen": exec: "mockgen": executable file not found in $PATH
pkg/remoteclient/remoteclient.go:3: running "mockgen": exec: "mockgen": executable file not found in $PATH
```
looks like we lost mockgen somewhere along the way

**Comment by staebler** [comment]
> ```
> hack/verify-generated.sh
> make[1]: Entering directory `/go/src/github.com/openshift/hive'
> go generate ./pkg/... ./cmd/...
> pkg/awsclient/client.go:51: running "mockgen": exec: "mockgen": executable file not found in $PATH
> pkg/controller/dnsendpoint/nameserver/query.go:7: running "mockgen": exec: "mockgen": executable file not found in $PATH
> pkg/controller/remotemachineset/actuator.go:11: running "mockgen": exec: "mockgen": executable file not found in $PATH
> pkg/gcpclient/client.go:19: running "mockgen": exec: "mockgen": executable file not found in $PATH
> pkg/remoteclient/remoteclient.go:3: running "mockgen": exec: "mockgen": executable file not found in $PATH
> ```
> 
> looks like we lost mockgen somewhere along the way

Yeah. This is included in the build image now. But that needs to come in as a separate PR first.

**Comment by staebler** [comment]
#806 needs to merge first to have the updated build image available for this PR.

**Pull request merged**
