### PR TITLE
Add ClusterRole RBAC for operator to create hive-admin.

### PR DESCRIPTION
**Pull request by dgoodwin**

### CODE REVIEW

**Comment by dgoodwin** [comment]
/test unit

???

**Comment by dgoodwin** [comment]
# github.com/openshift/hive/pkg/install (testmain)
/usr/local/go/pkg/tool/linux_amd64/link: flushing $WORK/b814/install.test: write $WORK/b814/install.test: cannot allocate memory
# github.com/openshift/hive/pkg/controller/federation (testmain)
/usr/local/go/pkg/tool/linux_amd64/link: flushing $WORK/b793/federation.test: write $WORK/b793/federation.test: cannot allocate memory
/usr/local/go/pkg/tool/linux_amd64/link: signal: killed

**Comment by csrwng** [comment]
@dgoodwin we may need to increase the memory request for the hive unit tests

**Pull request merged**
