### PR TITLE
upgrade kube to 1.17.1

### PR DESCRIPTION
**Pull request by staebler**
Upgrade kubernetes to 1.17.1.
Upgrade controller-runtime to 0.4.0.

Isolate the aggregate API server in a sub-module so that it can continue to use kube 1.14.1.

### CODE REVIEW

**Comment by staebler** [comment]
I removed a stray commit from #944 that had been accidentally added to this PR.

**Comment by staebler** [comment]
I pushed an update because I incorrectly thought that the readiness check was not getting set to ready until the pod acquire the leader role. However, I was just using an old image that did not have the readiness changes. I reverted the update, but this still needs another lgtm.

**Comment by staebler** [comment]
Rebased to address conflicts with #944.

**Comment by dgoodwin** [comment]
More conflicts :(

**Comment by staebler** [comment]
Rebased to address conflicts with #942.

**Comment by staebler** [comment]
github.com/openshift/library-go/pkg/controller/ownerref.go was removed from vendor somehow. I'm fixing it.

**Comment by staebler** [comment]
Rebased to fix the following.
* Vendor of github.com/openshift/library-go/pkg/controller.
* Change of ListOptionFunc to ListOption.
* Fix unit tests in pkg/controller/utils/ownership_test.go to handle TypeMeta and ResourceVersion being added to the resources.

**Pull request merged**
