### PR TITLE
Updates install dependencies.

### PR DESCRIPTION
**Pull request by jtudelag**
yq is needed.

### CODE REVIEW

**Comment by dgoodwin** [comment]
Is this because of it's use in hack/olm-registry-deploy.sh or somewhere else? I can't find much. I also don't have it installed. :)

**Comment by jtudelag** [comment]
@dgoodwin , yes, here: https://github.com/openshift/hive/blob/master/hack/olm-registry-deploy.sh#L41

**Comment by dgoodwin** [comment]
Can you clarify why you are using this script? This is used for our pipelines that deploy to dedicated, definitely not something I would expect a normal user or developer of hive to need to worry about.

**Comment by jtudelag** [comment]
@dgoodwin just wanted to deploy hive to play with it. Is there any easier way to do it?

**Comment by dgoodwin** [comment]
Today we use the methods referenced in the documentation, the OLM bundle building is more complex and only used in our pipelines right now, though we do plan to package as an OLM community operator and have work underway for that.

Recommended way today is to use the make deploy targets.

**Comment by jtudelag** [comment]
Thanks. Well, we can close this if you want then.

**Pull request closed without merging**
