### PR TITLE
remove v1alpha1 api server

### PR DESCRIPTION
**Pull request by staebler**
* Remove the code for the v1alpha1 api server.
* Remove the hiveAPIEnabled field from HiveConfig.
* Remove residual v1alpha1 migration scripts.

https://issues.redhat.com/browse/CO-869

### CODE REVIEW

**Comment by staebler** [comment]
/hold

We should disable the v1alpha1 API server in stage and int, then in prod, before merging this.

**Comment by staebler** [comment]
The conflicts have been resolved on these changes. I have broken the changes into 3 commits to make it a bit easier to review.

/cc @gregsheremeta

**Comment by gregsheremeta** [comment]
you definitely have my ack to merge it, but code review should come from someone qualified :)

**Comment by staebler** [comment]
@dgoodwin This needs another lgtm since there were some needed changes to the dockerfiles that were not included.

**Pull request merged**
