### PR TITLE
Add install error regex for AWSEC2QuotaExceeded

### PR DESCRIPTION
**Pull request by csheremeta**
see https://coreos.slack.com/archives/CCX9DB894/p1639325596354000

### CODE REVIEW

**Comment by csheremeta** [comment]
related: https://gitlab.cee.redhat.com/service/uhc-clusters-service/-/merge_requests/3548

**Comment by 2uasimojo** [comment]
- This is a dup of #1521.
- Please add a simple test case (see :arrow_up:)
- Also may want to consider the regex variations suggested there :arrow_up: 
- This will need a `make update` when you're done
- I'd like @gregsheremeta to look before we merge.

**Comment by 2uasimojo** [comment]
> * This is a dup of #1521.

...and this is the second dup I've seen (#1627). I'm starting to think y'all want this in. For the love of all that is holy, let's get *one* of these landed.

**Comment by gregsheremeta** [comment]
> this is the second dup I've seen

I like this one the best. The other two are now closed.

**Comment by gregsheremeta** [comment]
looks good to me after a test is added. I like this regexp the most -- it will catch specifically ec2, and it's not more precise than it needs to be

**Comment by gregsheremeta** [comment]
I'm sorry, there is a test. Looks good to me (leaving to @2uasimojo to tag it)

**Review by 2uasimojo — COMMENTED** [review]
/lgtm

thanks all

**Pull request merged**
