### PR TITLE
Add regex for AWS NLB creation installation failure

### PR DESCRIPTION
**Pull request by supreeth7**
Relates to: [OSD-9818](https://issues.redhat.com/browse/OSD-9818)

### CODE REVIEW

**Comment by supreeth7** [comment]
I'm not able to figure out what exactly is causing the e2e tests to fail. Can anyone having a look at this help perhaps?

**Comment by gregsheremeta** [comment]
lgtm

**Comment by 2uasimojo** [comment]
> I'm not able to figure out what exactly is causing the e2e tests to fail. Can anyone having a look at this help perhaps?

Flakes.

/test e2e

**Review by 2uasimojo — COMMENTED** [review]
/lgtm

**Comment by 2uasimojo** [comment]
/test e2e

I dunno, perhaps a rebase would help?

**Pull request merged**
