### PR TITLE
BZ2026853: Backport updating installer vendor to ad535d3.

### PR DESCRIPTION
**Pull request by abutcher**
Backports #1656.

[BZ 2026853](https://bugzilla.redhat.com/show_bug.cgi?id=2026853) needs a small change that was included in this vendor update. (https://github.com/openshift/installer/pull/5314)

I moved `go.mod` and `go.sum` changes to their own commits. Extra changes were needed around the `remotemachineset` controller which we've renamed to the `machinepool` controller upstream.

### CODE REVIEW

**Comment by 2uasimojo** [comment]
/lgtm

but

/hold -- I want to make sure azure and gcp e2es pass before we merge.

**Comment by 2uasimojo** [comment]
/lgtm cancel

[e2e-azure fail](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_hive/1694/pull-ci-openshift-hive-ocm-2.4-e2e-azure/1495805976949821440) looks legit.

**Comment by 2uasimojo** [comment]
Andrew rightly [points out](https://coreos.slack.com/archives/CE3ETN3J8/p1645478097860749?thread_ts=1645462987.535759&cid=CE3ETN3J8) that e2e-azure never worked on 2.4.

/lgtm

**Comment by abutcher** [comment]
Looks flaky
/test e2e-azure

**Pull request merged**
