### PR TITLE
Add hive-frontend role

### PR DESCRIPTION
**Pull request by dgoodwin**
@jhernand can you give this a look and let me know if it looks sufficient to you?

This may take some trial and error but the more we can get right now the better.

@jmelis you may want a look as well

### CODE REVIEW

**Comment by jhernand** [comment]
The permissions look good to me. However I wonder if we will be able/allowed to get those permissions inside an OpenShift dedicated cluster.

**Comment by dgoodwin** [comment]
This will deliver via OLM with hive -operator so we can literally add whatever we want here, and per Jira SRE has no issues with the elevated access at this time.

I am not sure if project requests are required. Should we add them for initial attempt?

**Comment by dgoodwin** [comment]
Ok then this is probably good for a first attempt. I will remove WIP and see if we can get it to roll out.

**Pull request merged**
