### PR TITLE
Remove replace statement from hive/apis

### PR DESCRIPTION
**Pull request by mjlshen**
This is just a proposal, so this is totally up for discussion, just my thoughts:

The existing replace statement doesn't seem to be strictly needed as we can just update the dependency when we are ready with `go get -u github.com/openshift/api@release-X.YY`. Furthermore, removing it makes importing Hive's API in other modules much easier as the replaces don't need to be carried forward.

E.g. https://github.com/openshift/osdctl/blob/115f5f5b8abea2956ad73845555bcc92bd1728b1/go.mod#L172 needs to maintain a corresponding replace.

Finally, by getting the latest `release-4.13` of `openshift/api`, we also pickup the latest dependencies from upstream K8s as they iterate on `golang.org/x/net` and `golang.org/x/text`

OCP 4.13 is needed specifically things like `machineapi.GCPShieldedInstanceConfig`, `machineapi.SecureBootPolicyEnabled`, and `machineapi.SecureBootPolicyEnabled` which aren't available in <= 4.12

### CODE REVIEW

**Comment by 2uasimojo** [comment]
No idea why that `replace` was put there originally; but if your proposal passes tests, I see no reason not to do it.

I think you'll need to make the same changes in the root go.mod as well though. Expect to see a `verify` failure in `modcheck`.

**Comment by mjlshen** [comment]
Looks like there are features used that require OCP 4.13, specifically things like `machineapi.GCPShieldedInstanceConfig`, `machineapi.SecureBootPolicyEnabled`, and `machineapi.SecureBootPolicyEnabled` so pinning to 4.13 instead.

The coverage failure is interesting, planning on looking at it a bit tomorrow

**Comment by mjlshen** [comment]
I can reproduce it! It's a flaky test due to a race condition:

```bash
cd ./apis
# Run this a couple times in a row
go test -race -count 50 -run TestGetName ./helpers
```

The errors often look like (but are not always consistent themselves):

```
--- FAIL: TestGetName (0.00s)
    namer_test.go:58: Got unexpected result. Expected: nv3nrxjzgyujzcs8gih1nc4gvx95bzirb13ohr3gdjy5jwlrjksduiakfd6upco4gxn8zb9dee9h3pn0yvlkpo8cw3yyp2j29xc0wrxoka00vdck6devixaoq0q-rzgma1kiyqtursiqmo8uoj3jwaiu9bja4ss92egv2z0ps1e8vtfihxmq2wvqezd-ohfw-i-quwxygmt2yqcmn1xsmp6jjrrb9nra2-iujsativs2bhq75u77-h6-omm0-deploy Got: nv3nrxjzgyujzcs8gih1nc4gvx95bzirb13ohr3gdjy5jwlrjksduiakfd6upco4gxn8zb9dee9h3pn0yvlkpo8cw3yyp2j29xc0wrxoka00vdck6devixaoq0q-rzgma1kiyqtursiqmo8uoj3jwaiu9bja4ss92egv2z0ps1e8vtfihxmq2wvqezd-ohfw-i-quwxygmt2yqcmn1xsmp6jjrrb9nra2-iujsativs2b-13a03bf3-deploy
    namer_test.go:58: Got unexpected result. Expected: nv3nrxjzgyujzcs8gih1nc4gvx95bzirb13ohr3gdjy5jwlrjksduiakfd6upco4gxn8zb9dee9h3pn0yvlkpo8cw3yyp2j29xc0wrxoka00vdck6devixaoq0q-rzgma1kiyqtursiqmo8uoj3jwaiu9bja4ss92egv2z0ps1e8vtfihxmq2wvqezd-ohfw-i-quwxygmt2yqcmn1xsmp6jjrrb9nra2-iujsativs2bhq75u77-h6-omm0-b46f2071 Got: nv3nrxjzgyujzcs8gih1nc4gvx95bzirb13ohr3gdjy5jwlrjksduiakfd6upco4gxn8zb9dee9h3pn0yvlkpo8cw3yyp2j29xc0wrxoka00vdck6devixaoq0q-rzgma1kiyqtursiqmo8uoj3jwaiu9bja4ss92egv2z0ps1e8vtfihxmq2wvqezd-ohfw-i-quwxygmt2yqcmn1xsmp6jjrrb9nra2-iujsativs2bhq75u77-b46f2071
```

**Comment by mjlshen** [comment]
/hold

Should wait for #1979 and be rebased to make sure tests pass

**Comment by 2uasimojo** [comment]
Yup, this is passing tests, and is rebased to pick up the go1.20 bump, so I'm happy with it. Thanks for doing this, @mjlshen. It makes our repo better.

/lgtm

**Pull request merged**
