### PR TITLE
Explicit pod security

### PR DESCRIPTION
**Pull request by 2uasimojo**
Conform to new pod security admission rules.

[HIVE-2023](https://issues.redhat.com//browse/HIVE-2023)

### CODE REVIEW

**Comment by 2uasimojo** [comment]
Note to future-me: I found violations as follows:

```
oc adm node-logs  $(oc get no -o name | paste -s -)  --path=kube-apiserver/audit.log|grep 'would violate PodSecurity' 
```

**Review by akhil-rane — COMMENTED** [review]
/lgtm

**Comment by 2uasimojo** [comment]
/hold

i give up until Monday

**Review by akhil-rane — COMMENTED** [review]
/lgtm

**Pull request merged**
