### PR TITLE
Revendor installer: OpenStack >=1 MachineSet

### PR DESCRIPTION
**Pull request by 2uasimojo**
We got unlucky when we revendored installer and picked up OCPBUGS-17064, which causes the MachineSets generator to produce zero MachineSets when the input specifies zero Replicas, as it does when we're autoscaling.

Revendor to the (current) tip of the 4.14 branch to pick up the fix.

[HIVE-2590](https://issues.redhat.com//browse/HIVE-2590)

### CODE REVIEW

**Comment by 2uasimojo** [comment]
/override ci/prow/security

#2387 (which might possibly work now that we've revendored installer here??)

**Comment by 2uasimojo** [comment]
/cherry-pick mce-2.4

I have a feeling we'll conflict in the vendor dirs, but it's worth a try :)

**Comment by dlom** [comment]
/lgtm

Vendoring the entire installer sucks and I wish there was a better way :/

**Comment by 2uasimojo** [comment]
Manually applied to mce-2.4 via #2438.

**Pull request merged**
