### PR TITLE
Remove ApplyOnce PatchApplyMode.

### PR DESCRIPTION
**Pull request by abutcher**
https://jira.coreos.com/browse/CO-499

### CODE REVIEW

**Comment by wanghaoran1988** [comment]
This is already being used by SRE team, I am still not clear why we need remove this, if we have to remove this, do we have a replaceable option for this?

**Comment by jewzaam** [comment]
Commented in JIRA, we use ApplyOnce at this time and need to test / transition off of it before this can merge.
/hold

**Comment by dgoodwin** [comment]
PR now targets V1, so we are going to merge and then fight about it with SRE if it becomes apparent they must have apply once patching in v1. :)

/lgtm

**Comment by jewzaam** [comment]
@dgoodwin fwiw, we removed use of `ApplyOnce`: https://github.com/openshift/managed-cluster-config/pull/141

**Comment by dgoodwin** [comment]
Awesome, thanks!

**Pull request merged**
