### PR TITLE
Fix CSV_FILE name substitution in hack/olm-registry-deploy.sh

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**
Fixes issue: https://github.com/openshift/hive/issues/911

### CODE REVIEW

**Comment by gregsheremeta** [comment]
Thanks. I recommend using https://operatorhub.io/operator/hive-operator

**Comment by dgoodwin** [comment]
This change looks correct, I believe olm-registry-deploy is not used by anything in the pipelines just Hive devs, thus why this has lingered so long.

/lgtm

**Pull request merged**
