### PR TITLE
Add counter metric for remote cluster client creation.

### PR DESCRIPTION
**Pull request by dgoodwin**

### CODE REVIEW

**Comment by csrwng** [comment]
@dgoodwin I'd like to better understand what we expect to get from this metric. We could create many remote clients without making a single call to them. Don't we want to know what actual calls we make?

**Comment by dgoodwin** [comment]
Perfect world I'd love metrics on the actual calls we use but I didnt see
an easy way to wrap it. Client creation was just an indicator that I
thought might expose problems but it's possibly already covered by
reconcile counters in each controller.

**Comment by csrwng** [comment]
@dgoodwin an idea to accomplish this is to wrap the client config's RoundTripper with our own. Every time a RoundTrip(*Request) function is called on it, simply increment a counter.

**Comment by dgoodwin** [comment]
Closing for reconsideration. Thanks.

**Pull request closed without merging**
