### PR TITLE
docs: debug hive does not request scale down to 0.

### PR DESCRIPTION
**Pull request by gyliu513**
Hive will be restarted automatically after edit finished.

/cc @LalatenduMohanty

### CODE REVIEW

**Comment by dgoodwin** [comment]
/hold

Sorry I think the docs might be correct, there are two Deployments in play. hive-operator is responsible for creating and maintaining hive-controllers, if you just edit hive-controllers and the operator is still running, on the next reconciling it will revert your change and you'll lose your debug logging. 

Unless I'm mistaken and the semantics of kubectl apply won't clobber that new option, but from what I recall it would.

**Comment by staebler** [comment]
Oh, right. I missed that important detail.

/lgtm cancel

**Comment by gyliu513** [comment]
Ah, I see, thanks @dgoodwin and @staebler , let me close this PR :-)

**Pull request closed without merging**
