### PR TITLE
prefer generic InconsistentTerraformResult install log regexp

### PR DESCRIPTION
**Pull request by gregsheremeta**
there were two specific terraform race related regexps in the list,
but new ones are popping up every day. replace with a generic
catch-all InconsistentTerraformResult code.

/assign @2uasimojo

### CODE REVIEW

**Review by 2uasimojo — COMMENTED** [review]
If you say it should be thus...

...but you need to `make update-gofmt`

**Comment by gregsheremeta** [comment]
> If you say it should be thus...

yeah, generic is better because the overall problem is "terraform issues" and in manifests in new ways -- we find a new one every day at this point. Today's example
https://bugzilla.redhat.com/show_bug.cgi?id=2047741

**Comment by 2uasimojo** [comment]
> ...but you need to `make update-gofmt`

Still this.

**Comment by 2uasimojo** [comment]
/lgtm

if CI is happy.

**Pull request merged**
