### PR TITLE
Switch to FROM centos:7 and restore libvirt dependencies.

### PR DESCRIPTION
**Pull request by dgoodwin**
Needs #818

### CODE REVIEW

**Comment by gregsheremeta** [comment]
what's the reason?

**Comment by dgoodwin** [comment]
libvirt deps cannot be installed in the universal base image, they're not available, and use of any other RHEL based build will fail locally and in appsre pipelines due to lack of entitlements.

ART docs appear to indicate our upstream images can and should be based on centos. They override the FROM during CI builds so they're ultimately RHEL but using centos upstream lets things like this work.

**Comment by dgoodwin** [comment]
Need an ack here before bare metal works again.

**Pull request merged**
