### PR TITLE
Correct versionFromGit for builds

### PR DESCRIPTION
**Pull request by 2uasimojo**
Set `SOURCE_GIT_TAG` to cause builds to get the proper `versionFromGit`
tag corresponding to what would show up in OperatorHub.

For "normal" bulids (OSD, OperatorHub) this results in the first log line for hive-operator and hive-controllers looking like:

```
time="2022-04-29T19:59:37Z" level=info msg="Version: openshift/hive v1.2.3606-aca223c"
```

For local builds on commits not tracking `master` you might see something like:

```
time="2022-04-29T19:51:08Z" level=info msg="Version: openshift/hive vUnknownBranch.3509-13b0fbf"
```

i.e. `UnknownBranch` instead of a `{major}.{minor}`. However, the commit count and sha should still be accurate.

[HIVE-1717](https://issues.redhat.com//browse/HIVE-1717)

### CODE REVIEW

**Comment by abutcher** [comment]
Copied `hack/version.py` to the master branch to test version matches current operator hub (`v1.2.3606-2544e8a`).

/lgtm

**Comment by 2uasimojo** [comment]
So yeah, this didn't work for OSD. On hives02ue1:
```
[efried@efried hive]$ oc logs -n hive deploy/hive-operator | head -1
time="2022-05-03T21:15:42Z" level=info msg="Version: openshift/hive v"
```
Need to look into the appsre build logs first to figure out what went wrong.

**Comment by 2uasimojo** [comment]
FUP to fix: #1759.

**Pull request merged**
