### PR TITLE
make Provisioning and InstallConfigSecretRef.Name required

### PR DESCRIPTION
**Pull request by gregsheremeta**
make Provisioning and InstallConfigSecretRef.Name required

### CODE REVIEW

**Comment by dgoodwin** [comment]
I thought these were optional for the adoption use case.

**Comment by dgoodwin** [comment]
Oh I see its only  for uninstalled clusters.

**Comment by gregsheremeta** [comment]
@dgoodwin should I edit the subject? "... for uninstalled clusters."

**Comment by dgoodwin** [comment]
Nah its ok.

**Pull request merged**
