### PR TITLE
operator bundle 1.0.2

### PR DESCRIPTION
**Pull request by gregsheremeta**
operator bundle 1.0.2

/cc @dgoodwin

### CODE REVIEW

**Comment by gregsheremeta** [comment]
diff between `1.0.1` and `1.0.2`:
```
diff ../1.0.1/hive-operator.v1.0.1.clusterserviceversion.yaml hive-operator.v1.0.2.clusterserviceversion.yaml 
9,10c9,10
<     containerImage: quay.io/openshift-hive/hive:v1.0.1
<     createdAt: '2020-04-13T11:04:38Z'
---
>     containerImage: quay.io/openshift-hive/hive:v1.0.2
>     createdAt: '2020-04-20T14:04:36Z'
13,14c13,14
<     support: OpenShift Hive Team
<   name: hive-operator.v1.0.1
---
>     support: Hive Team
>   name: hive-operator.v1.0.2
24c24
<   description: "OpenShift Hive is an operator that runs on top of Kubernetes/OpenShift.\
---
>   description: "Hive for Red Hat OpenShift is an operator that runs on top of Kubernetes/OpenShift.\
36,43c36,43
<     \ OpenShift Hive operator, create a cluster-scoped `HiveConfig` CR to configure\
<     \ Hive.\nUpon creation of `HiveConfig`, the operator will configure Hive's pods.\n\
<     \nExample `HiveConfig`:\n```yaml\n---\n  apiVersion: hive.openshift.io/v1\n  kind:\
<     \ HiveConfig\n  metadata:\n    name: hive\n  spec:\n    managedDomains:\n    -\
<     \ aws:\n        credentialsSecretRef:\n          name: my-route53-creds\n    \
<     \  domains:\n      - my-base-domain.example.com\n```\n\n## Create a cluster\n\n\
<     To create a cluster with Hive, create a `ClusterDeployment` CR. You can also use\
<     \ the\n[`hiveutil` tool](https://github.com/openshift/hive/blob/master/docs/hiveutil.md)'s\
---
>     \ Hive for Red Hat OpenShift operator, create a cluster-scoped `HiveConfig` CR\
>     \ to configure Hive.\nUpon creation of `HiveConfig`, the operator will configure\
>     \ Hive's pods.\n\nExample `HiveConfig`:\n```yaml\n---\n  apiVersion: hive.openshift.io/v1\n\
>     \  kind: HiveConfig\n  metadata:\n    name: hive\n  spec:\n    managedDomains:\n\
>     \    - aws:\n        credentialsSecretRef:\n          name: my-route53-creds\n\
>     \      domains:\n      - my-base-domain.example.com\n```\n\n## Create a cluster\n\
>     \nTo create a cluster with Hive, create a `ClusterDeployment` CR. You can also\
>     \ use the\n[`hiveutil` tool](https://github.com/openshift/hive/blob/master/docs/hiveutil.md)'s\
45c45
<   displayName: OpenShift Hive
---
>   displayName: Hive for Red Hat OpenShift
246c246
<                 image: quay.io/openshift-hive/hive:v1.0.1
---
>                 image: quay.io/openshift-hive/hive:v1.0.2
249d248
<                   failureThreshold: 1
251c250
<                     path: /debug/health
---
>                     path: /healthz
253,254d251
<                   initialDelaySeconds: 10
<                   periodSeconds: 10
255a253,256
>                 readinessProbe:
>                   httpGet:
>                     path: /readyz
>                     port: 8080
284c285
<   - name: OpenShift Hive GitHub
---
>   - name: Hive GitHub
286c287
<   - name: 'OpenShift Hive: Cluster-as-a-Service'
---
>   - name: 'Hive: Cluster-as-a-Service'
291c292,293
<   - name: OpenShift Hive Team
---
>   - email: openshift-hive-team@redhat.com
>     name: Hive Team
295,296c297,298
<   replaces: hive-operator.v1.0.0
<   version: 1.0.1
---
>   replaces: hive-operator.v1.0.1
>   version: 1.0.2

```

**Comment by gregsheremeta** [comment]
/cc @staebler 
so you can review the changes from #935 that this picks up. CSV deployment has your changes.

**Comment by staebler** [comment]
> /cc @staebler
> so you can review the changes from #935 that this picks up. CSV deployment has your changes.

The deployment changes look good.

**Pull request merged**
