### PR TITLE
More install log regexps

### PR DESCRIPTION
**Pull request by gregsheremeta**
best to review commit by commit

/assign @2uasimojo 
/cc @yithian

### CODE REVIEW

**Comment by yithian** [comment]
seems sane to me fwiw

**Comment by 2uasimojo** [comment]
Pretty sure the CI fails are legit.

/hold

to stop eating CI resources.

**Comment by abutcher** [comment]
@2uasimojo Pushed a fix to @gregsheremeta's branch after checking with him. I'm not going to lgtm my own push so will wait for you to review.

**Comment by gregsheremeta** [comment]
thanks!

**Pull request merged**
