### PR TITLE
Generate Installer's InstallConfig and Mount in Installer Pod

### PR DESCRIPTION
**Pull request by dgoodwin**
Restores the ConfigMap containing a install config, now converts our config to the very similar installer InstallConfig.

### CODE REVIEW

**Comment by csrwng** [comment]
Looks like you need to rebase but lgtm

**Comment by dgoodwin** [comment]
Conflicts resolved. I *think* overlapping mounts is ok, I was able to find references to bugs with it being fixed :) and it appears to work now.

**Comment by dgoodwin** [comment]
Going to remove the overlapping mount in next PR anyhow, just realized I need to copy the install config due to how the installer wants to use and delete it, and the fact we're trying to share the output volume. Will put it somewhere else, and hiveutil will copy it in.

**Pull request merged**
