### PR TITLE
RHTAP Configurations

### PR DESCRIPTION
**Pull request by gbenhaim**
Add the required configurations for RHTAP's build pipelines.

### CODE REVIEW

**Comment by 2uasimojo** [comment]
/test unit

Known flake, tracked via https://issues.redhat.com/browse/HIVE-2279

**Comment by gbenhaim** [comment]
@2uasimojo any idea why the build is failing with multiple errors about vendor dependencies? here is an example of one
```
vendor/github.com/microsoftgraph/msgraph-sdk-go/users/item/contactfolders/item/childfolders/item/contacts/item/photo/photo_request_builder.go:8:5: cannot query module due to -mod=vendor
```

**Comment by 2uasimojo** [comment]
> @2uasimojo any idea why the build is failing with multiple errors about vendor dependencies? here is an example of one
> 
> ```
> vendor/github.com/microsoftgraph/msgraph-sdk-go/users/item/contactfolders/item/childfolders/item/contacts/item/photo/photo_request_builder.go:8:5: cannot query module due to -mod=vendor
> ```

@gbenhaim I'm getting an auth error trying to see [build-container](https://console-openshift-console.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/k8s/ns/crt-redhat-acm-tenant/tekton.dev~v1beta1~PipelineRun/hive-master-on-pull-request-k72nv/logs/build-container).

When I run `make build` locally I do see us passing `-mod=vendor` to `go build`, but I'm not seeing this error. However, in our app-sre pipeline it looks like our build is *not* passing `-mod=vendor` ([example](https://ci.int.devshift.net/job/openshift-hive-gh-build-master/896/console)) and that's passing as well :shrug:.

If you can share the actual build log (or better yet, give me & the hive team the necessary access) I can take a closer look.

**Comment by gbenhaim** [comment]
@2uasimojo please let me know if the following link doesn't work for you https://console.redhat.com/preview/hac/application-pipeline/workspaces/crt-redhat-acm/applications/hive/pipelineruns/hive-master-on-pull-request-k72nv/logs

**Comment by 2uasimojo** [comment]
@gbenhaim it does work; but I'm only seeing `hive` and `hive-1`. The latest builds for both are June 20th, which says to me that I'm not looking at the right thing? (I see `hive` was attached to #2051. `hive-1` says "manual build".)

**Comment by gbenhaim** [comment]
The build is passing now `Red Hat Trusted App Pipeline / hive-master-on-pull-request Successful in 25m — Success`

**Comment by gbenhaim** [comment]
this one `Red Hat Trusted App Pipeline Failing after 24385m — Failed` isn't applicable anymore and can be ignored.

**Comment by 2uasimojo** [comment]
@gbenhaim I'm kind of just watching this work from the sidelines. From what I can tell, we're still not ready to take the next step -- whatever that may be. Please let me know if/when we get to that point, and what that should look like. (Feel free to schedule a Meet™ if it would be easier to talk through that way.)

**Pull request closed without merging**
