### PR TITLE
Run generate  bydefult before verify

### PR DESCRIPTION
**Pull request by LalatenduMohanty**

### CODE REVIEW

**Comment by csrwng** [comment]
@LalatenduMohanty did you intend to include the 2 commits in this PR?

**Comment by LalatenduMohanty** [comment]
> @LalatenduMohanty did you intend to include the 2 commits in this PR?

Nope, it was a mistake. Fixed it.

**Comment by csrwng** [comment]
So we already invoke generate as part of the all target because build (manager, operator, etc) depends on it. Is the purpose of this to run generate before the verify test?

**Comment by LalatenduMohanty** [comment]
> Is the purpose of this to run generate before the verify test?

Right. Else it fails in verify if changes supposed to be done in `generate`. So why not make it generate before verify?

**Comment by csrwng** [comment]
> Right. Else it fails in verify if changes supposed to be done in `generate`. So why not make it generate before verify?

That's fine, just wanted to understand why you're adding it.

/lgtm

**Pull request merged**
