### PR TITLE
syncset controller: Restore reconcile duration metric

### PR DESCRIPTION
**Pull request by 2uasimojo**
This was (accidentally, we think?) removed via 70c7ae2e6e52ef493d6b6a487ca1d8c1aac6f927 in [#437](https://github.com/openshift/hive/pull/437/files#diff-6f5e4dec9c039eb5be5eed0036fc3604L170-L182)

### CODE REVIEW

**Comment by 2uasimojo** [comment]
@dgoodwin might want :eyes: since you set up the original metrics via #446.

**Comment by staebler** [comment]
The syncset controller should almost certainly be adding metrics.

/hold cancel

**Comment by dgoodwin** [comment]
Nice catch, thanks @2uasimojo

**Pull request merged**
