### PR TITLE
hive-frontend add events to role

### PR DESCRIPTION
**Pull request by maorfr**
This pR allows the hive-frontend ServiceAccount to manage Events.
This is required for https://jira.coreos.com/browse/APPSRE-882

Please let us know if that is the correct way to achieve this.

Thanks!

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
It should have been a single commit we do not need two commits for the change, missed that in the review.

**Comment by maorfr** [comment]
sorry about that :|

**Pull request merged**
