### PR TITLE
Add FAILED_PROVISION_CONFIG param to hivconfig template.

### PR DESCRIPTION
**Pull request by twiest**
This is necessary in order to deploy S3 log uploading.

/assign @gregsheremeta 
/cc @joelddiaz

### CODE REVIEW

**Comment by twiest** [comment]
@jmelis Please take a look and make sure that this looks right. There's a corresponding MR that I'll tag you in as well.

**Comment by gregsheremeta** [comment]
lgtm

i'm ok if we don't wait for Jaime...

**Review by joelddiaz — COMMENTED** [review]
:+1: not sure if we're waiting on anything else here, but this looks fine to me.

**Comment by twiest** [comment]
Waiting for @jmelis to weigh in on this and the other MR.

/hold

**Comment by twiest** [comment]
2020/12/02 20:31:27 error: Failed to acquire resource, current capacity: 0 free, 150 leased

/test e2e

**Comment by twiest** [comment]
level=fatal msg="failed to fetch Common Manifests: failed to fetch dependency of \"Common Manifests\": failed to generate asset \"DNS Config\": getting public zone for \"eontylcq.hive-ci.openshift.com\": listing hosted zones: Throttling: Rate exceeded\n\tstatus code: 400, request id: f3033d15-4efa-4ff6-82db-ace4a1a49645"

/test e2e

**Comment by twiest** [comment]
level=fatal msg="failed to fetch Common Manifests: failed to fetch dependency of \"Common Manifests\": failed to generate asset \"DNS Config\": getting public zone for \"gkazsqfs.hive-ci.openshift.com\": listing hosted zones: Throttling: Rate exceeded\n\tstatus code: 400, request id: 0b71081f-87c4-40ac-aa86-284218125d79"

/test e2e

**Comment by twiest** [comment]
Removing hold as I missed @gregsheremeta's comment above about not needing to wait for Jaime.

/hold cancel

**Pull request merged**
