### PR TITLE
Fix layout for kustomize 2.0.0

### PR DESCRIPTION
**Pull request by twiest**
- [x] Fix layout for kustomize 2.0.0
- [x] Lock e2e test to kustomize 2.0.0
- [x] Test asset generation with new kustomize file and locations.
- [x] Test deploy with new kustomize file and locations.

### CODE REVIEW

**Comment by csrwng** [comment]
I think we need to increase the resource reqs for our unit tests to prevent timeouts

**Comment by csrwng** [comment]
@twiest @dgoodwin looks like our generated install-config is out of sync with the one from the installer
```
level=debug msg="Generating \"Terraform Variables\"..."
panic: interface conversion: runtime.Object is nil, not *v1alpha1.AWSMachineProviderConfig

goroutine 1 [running]:
github.com/openshift/installer/pkg/asset/cluster.(*TerraformVariables).Generate(0x862e450, 0xc420888cc0, 0xc420c1b9f0, 0x2)
	/go/src/github.com/openshift/installer/pkg/asset/cluster/tfvars.go:109 +0x1399
github.com/openshift/installer/pkg/asset/store.(*storeImpl).fetch(0xc4203d09f0, 0x51b1180, 0x862e450, 0x0, 0x0, 0x44db1e0, 0x461f9c0)
	/go/src/github.com/openshift/installer/pkg/asset/store/store.go:226 +0x7c0
github.com/openshift/installer/pkg/asset/store.(*storeImpl).Fetch(0xc4203d09f0, 0x51b1180, 0x862e450, 0x51b1180, 0x862e450)
	/go/src/github.com/openshift/installer/pkg/asset/store/store.go:76 +0x4b
main.runTargetCmd.func1(0x7fff5f9cd45f, 0x7, 0xc4203ed420, 0xc42097bbf8)
	/go/src/github.com/openshift/installer/cmd/openshift-install/create.go:157 +0x13f
main.runTargetCmd.func2(0x8606940, 0xc420680c00, 0x0, 0x4)
	/go/src/github.com/openshift/installer/cmd/openshift-install/create.go:182 +0x81
github.com/openshift/installer/vendor/github.com/spf13/cobra.(*Command).execute(0x8606940, 0xc420680bc0, 0x4, 0x4, 0x8606940, 0xc420680bc0)
	/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/openshift/installer/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4203be500, 0x0, 0xc4203bf680, 0xc4203be650)
	/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/openshift/installer/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4203be500, 0xc42097beb8, 0x1)
	/go/src/github.com/openshift/installer/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.installerMain()
	/go/src/github.com/openshift/installer/cmd/openshift-install/main.go:56 +0x132
main.main()
	/go/src/github.com/openshift/installer/cmd/openshift-install/main.go:40 +0x9b
```

**Comment by dgoodwin** [comment]
I will take a look this morning.

**Comment by dgoodwin** [comment]
It's probably this: https://github.com/openshift/installer/pull/1175

**Comment by dgoodwin** [comment]
https://github.com/openshift/installer/issues/1205

**Pull request merged**
