### PR TITLE
Skip configuring CA when object already exists

### PR DESCRIPTION
**Pull request by osherdp**
This leaves ``ClusterAutoscaler`` with its existing configuration in case it's already defined in the cluster.
Creation of the object with the same defaults will still take place as before, in case cluster still doesn't have it defined.

Closes [HIVE-2220](https://issues.redhat.com//browse/HIVE-2220)

### CODE REVIEW

**Comment by osherdp** [comment]
```
admission_test.go:91: Unexpected create error: dnszonevalidators.admission.hive.openshift.io is forbidden: User "system:anonymous" cannot create resource "dnszonevalidators" in API group "admission.hive.openshift.io" at the cluster scope
```
(from [here](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_hive/2025/pull-ci-openshift-hive-master-e2e/1659092055336423424))

I don't find it related to my changes. I'll try to retest to see if it reoccurs 
/test e2e

**Comment by osherdp** [comment]
/test e2e
seems like another flake. I'll ask in slack if someone knows of this one

**Comment by 2uasimojo** [comment]
/test e2e-pool

known flake, investigating/fixing via #2021.

**Comment by 2uasimojo** [comment]
/lgtm

If CI is happy, I'm happy.

**NOTE:** this unwinds behavior from #735 and #1833 / HIVE-1976.

**Pull request merged**
