### PR TITLE
vendor: Update the installer to get additional AWS deletion

### PR DESCRIPTION
**Pull request by wking**
Generated with:

```console
$ dep ensure -update
```

using:

```console
$ dep version
dep:
 version     : v0.5.0-31-g73b3afe
 build date  : 2019-02-08
 git hash    : 73b3afe
 go version  : go1.10.3
 go compiler : gc
 platform    : linux/amd64
 features    : ImportDuringSolve=false
```

Pulling in snapshot (openshift/installer#1346) and network-interface (openshift/installer#1361) deletion.

### CODE REVIEW

**Comment by wking** [comment]
[unit][1]:

```
go generate ./pkg/... ./cmd/...
F0305 13:38:02.614534     438 deepcopy.go:805] Hit an unsupported type invalid type.
exit status 255
```

may be due to an alias type (kubernetes-incubator/apiserver-builder-alpha#279).  Probably something I pulled in with:

```console
$ git show --stat=200 --oneline vendor/k8s.io/gengo
581f0f71 (HEAD -> network-interface-deletion, wking/network-interface-deletion) vendor: Update, including the installer deletion package
 vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go | 101 ++++++++++++++++++++++++++++++++++++++++++++++++++++++-----------------------------------------------
 vendor/k8s.io/gengo/generator/execute.go                         |   8 ++++----
 vendor/k8s.io/gengo/generator/import_tracker.go                  |   4 ++--
 vendor/k8s.io/gengo/parser/parse.go                              |  44 ++++++++++++++++++++++----------------------
 vendor/k8s.io/gengo/types/types.go                               |   4 ++--
 5 files changed, 84 insertions(+), 77 deletions(-)
lines 1-7/7 (END)
```

Unfortunately, we can't pin to our old version:

```console
$ git diff -U0 Gopkg.toml  | cat
diff --git a/Gopkg.toml b/Gopkg.toml
index 2cea53c1..bc4125d2 100644
--- a/Gopkg.toml
+++ b/Gopkg.toml
@@ -81,0 +82,4 @@ version="v1.4.7"
+[[override]]
+  name = "k8s.io/gengo"
+  revision = "4242d8e6c5dba56827bb7bcf14ad11cda38f3991"
+
$ dep ensure
$ make generate
$ make generate
go generate ./pkg/... ./cmd/...
/tmp/go-build937090372/b001/exe/main flag redefined: log_dir
panic: /tmp/go-build937090372/b001/exe/main flag redefined: log_dir

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc42007c060, 0x7cf540, 0x96f6f0, 0x777633, 0x7, 0x79ed34, 0x2f)
	/home/trking/.local/go/src/flag/flag.go:810 +0x540
flag.(*FlagSet).StringVar(0xc42007c060, 0x96f6f0, 0x777633, 0x7, 0x0, 0x0, 0x79ed34, 0x2f)
	/home/trking/.local/go/src/flag/flag.go:713 +0x8b
github.com/openshift/hive/vendor/k8s.io/klog.InitFlags(0xc42007c060)
	/home/trking/.local/lib/go/src/github.com/openshift/hive/vendor/k8s.io/klog/klog.go:411 +0x7b
main.main()
	/home/trking/.local/lib/go/src/github.com/openshift/hive/vendor/k8s.io/code-generator/cmd/deepcopy-gen/main.go:59 +0x3c
exit status 2
pkg/apis/apis.go:18: running "go": exit status 1
make: *** [generate] Error 1
```

And we can't pin to the commit that landed the klog migration, since it already has the bug:

```console
$ git diff -U0 Gopkg.toml |cat
diff --git a/Gopkg.toml b/Gopkg.toml
index 2cea53c1..27f07909 100644
--- a/Gopkg.toml
+++ b/Gopkg.toml
@@ -81,0 +82,4 @@ version="v1.4.7"
+[[override]]
+  name = "k8s.io/gengo"
+  revision = "51747d6e00da1fc578d5a333a93bb2abcbce7a95"
+
$ dep ensure
$ make generate
go generate ./pkg/... ./cmd/...
F0305 09:25:17.088530   29291 deepcopy.go:798] Hit an unsupported type invalid type.
exit status 255
pkg/apis/apis.go:18: running "go": exit status 1
make: *** [generate] Error 1
```

So I guess we'd have to pin the other klog consumers too:

```console
$ git grep k8s.io/klog vendor | cat
vendor/github.com/openshift/cluster-api/pkg/apis/machine/common/plugins.go:	"k8s.io/klog"
vendor/k8s.io/code-generator/cmd/deepcopy-gen/main.go:	"k8s.io/klog"
```

Ugh, pinning openshift/cluster-api is not appealing.  I guess we need to get the generator fixed?  Add manually-coded deep-copy methods for the troublesome types?  Something else?

[1]: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_hive/245/pull-ci-openshift-hive-master-unit/562/build-log.txt

**Comment by dgoodwin** [comment]
Can we update the revision for installer to master's hash, dep ensure, and leave other deps alone for now?

**Comment by wking** [comment]
> Can we update the revision for installer to master's hash, dep ensure, and leave other deps alone for now?

Sure, done with 581f0f71 -> 58784247.  See the commit message for details, but I stopped just short of openshift/installer#1356's v1beta4.

**Comment by dgoodwin** [comment]
Thanks @wking

**Pull request merged**
