### PR TITLE
Modifying some debug messages to info in dnszone controller

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
It will help getting more useful information in the controller logs

Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

### CODE REVIEW

**Comment by dgoodwin** [comment]
It looks like I failed to submit my comment last week, but in addition to this it appears we have no logging when we fail to resolve the hostname. Please locate that point in the file and add an info line there as well, that will help us if this pops up again.

**Comment by LalatenduMohanty** [comment]
> It looks like I failed to submit my comment last week, but in addition to this it appears we have no logging when we fail to resolve the hostname. Please locate that point in the file and add an info line there as well, that will help us if this pops up again.

I have added a log info for `SOA record for DNS zone not available`, please take a look.

**Pull request merged**
