### PR TITLE
bundle-gen: Add --dummy-bundle COMMIT-ISH (for MCE)

### PR DESCRIPTION
**Pull request by 2uasimojo**
Add support to hack/bundle-gen.py for generating bundle files locally,
from an arbitrary commit. The result is *not* a real OLM bundle; this is
explicitly for the case where hive is to be packaged into a larger
deliverable (specifically MCE). Of note, this option does not:
- Try to compute a real `version`. The `name` and `version` fields in
the CSV should be seen as placeholders, to be supplanted by the
consuming packaging.
- Build/push operator images.
- Talk to OperatorHub to a) calculate graph data (e.g. `replaces`), or
b) open PRs.

Example usage below. Note that the argument to `--dummy-bundle` can be
any commit-ish recognized by git, including a raw SHA.
```
[efried@efried hive]$ ./hack/bundle-gen.py --dummy-bundle origin/ocm-2.4
Cloning git@github.com:openshift/hive.git to /tmp/hive-repo-wwo7fkwx
Working in /tmp/hive-repo-wwo7fkwx
Checking out https://github.com/2uasimojo/hive/commit/74831db3a27301cc195ef4e78a43ebab36b10e9c
Skipping build of container quay.io/openshift-hive/hive:v0.0.3227-74831db
Writing bundle files to directory: /tmp/hive-operator-bundle-rq3_t5ua
Generating CSV for version: 0.0.3227-74831db
Wrote ClusterServiceVersion: /tmp/hive-operator-bundle-rq3_t5ua/0.0.3227-74831db/hive-operator.v0.0.3227-74831db.clusterserviceversion.yaml
Wrote bundle to /home/efried/go/src/github.com/openshift/hive/hive-operator-bundle-0.0.3227-74831db
[efried@efried hive]$ ll hive-operator-bundle-0.0.3227-74831db/
total 384
drwxrwxr-x.  2 efried efried  4096 Jul  7 10:16 ./
drwxrwxr-x. 18 efried efried  4096 Jul  7 10:16 ../
-rw-rw-r--.  1 efried efried  2062 Jul  7 10:16 hiveinternal.openshift.io_clustersyncleases.yaml
-rw-rw-r--.  1 efried efried 10938 Jul  7 10:16 hiveinternal.openshift.io_clustersyncs.yaml
-rw-rw-r--.  1 efried efried  7089 Jul  7 10:16 hiveinternal.openshift.io_fakeclusterinstalls.yaml
-rw-rw-r--.  1 efried efried  2783 Jul  7 10:16 hive.openshift.io_checkpoints.yaml
-rw-rw-r--.  1 efried efried  7542 Jul  7 10:16 hive.openshift.io_clusterclaims.yaml
-rw-rw-r--.  1 efried efried 57511 Jul  7 10:16 hive.openshift.io_clusterdeployments.yaml
-rw-rw-r--.  1 efried efried 14096 Jul  7 10:16 hive.openshift.io_clusterdeprovisions.yaml
-rw-rw-r--.  1 efried efried  2218 Jul  7 10:16 hive.openshift.io_clusterimagesets.yaml
-rw-rw-r--.  1 efried efried 30138 Jul  7 10:16 hive.openshift.io_clusterpools.yaml
-rw-rw-r--.  1 efried efried  7567 Jul  7 10:16 hive.openshift.io_clusterprovisions.yaml
-rw-rw-r--.  1 efried efried  5142 Jul  7 10:16 hive.openshift.io_clusterrelocates.yaml
-rw-rw-r--.  1 efried efried  4534 Jul  7 10:16 hive.openshift.io_clusterstates.yaml
-rw-rw-r--.  1 efried efried 11198 Jul  7 10:16 hive.openshift.io_dnszones.yaml
-rw-rw-r--.  1 efried efried 36393 Jul  7 10:16 hive.openshift.io_hiveconfigs.yaml
-rw-rw-r--.  1 efried efried  2577 Jul  7 10:16 hive.openshift.io_machinepoolnameleases.yaml
-rw-rw-r--.  1 efried efried 23401 Jul  7 10:16 hive.openshift.io_machinepools.yaml
-rw-rw-r--.  1 efried efried 36537 Jul  7 10:16 hive.openshift.io_selectorsyncidentityproviders.yaml
-rw-rw-r--.  1 efried efried  9783 Jul  7 10:16 hive.openshift.io_selectorsyncsets.yaml
-rw-rw-r--.  1 efried efried 34985 Jul  7 10:16 hive.openshift.io_syncidentityproviders.yaml
-rw-rw-r--.  1 efried efried  8176 Jul  7 10:16 hive.openshift.io_syncsets.yaml
-rw-rw-r--.  1 efried efried 34099 Jul  7 10:16 hive-operator.v0.0.3227-74831db.clusterserviceversion.yaml
```

[HIVE-1954](https://issues.redhat.com//browse/HIVE-1954)

### CODE REVIEW

**Comment by joeg-pro** [comment]
@2uasimojo Some thoughts:

Re the `--branch ocm-2.5-mce-2.0 ` option. shown  As I have learned in the last 5 hours, the MCE build is managed by my team as one that essentially "pins" what it is getting from the Hive upstream by specifying a particular Git SHA, with that Git SHA updated when advised "its time to pick up new code".  (Rather than track a branch continuously, we "lurch forward" from time to time, I guess.)

In light of that, could there be a `--sha` option to allow us to specify that.  Or maybe we already can have that because the the `--branch` option can be "abused" by specifying a Git SHA rather than a branch name?

**Comment by 2uasimojo** [comment]
@joeg-pro
### package.yaml
Roger wilco, I'll rip it out and collapse.

### branch/sha
We use the branch to compute the version and the channel. That code is pretty complicated (and kind of brittle tbh). We've played with accepting just a SHA, but the resulting version/channel can be... unpredictable.

I guess we could let you specify the `--version-base` (the `X.Y` part of the semver) and a `--commit`; and if we're not producing the package.yaml (see above) we don't need a channel name. I'll want to do some extra arg validation: in `--bundle-only` mode you'll be _required_ to specify `--version-base`, `--sha`, and `--replaces`. Will that work for you?

/hold

**Comment by joeg-pro** [comment]
Sorry for delay, was out on PTO for a couple of days around 4th of July.

> We use the branch to compute the version and the channel.

Yea, I understand, as I think I do about the same thing in the tooling that pulls together the overall ACM or MCE bundles.

>  I guess we could let you specify the --version-base (the X.Y part of the semver) and a --commit; and if we're not producing the package.yaml (see above) we don't need a channel name. I'll want to do some extra arg validation

So thinking about this a bit more,  when we invoke with `--bundle-only` we aren't going to care about the `spec.version` in the resulting CSV, nor 
having a reasonable version as part of the CSV name in `spec.name`, nor needing reasonable OLM replacement graph info (replaces, skipRange) nor a reasonable channel name.  As we merge your bundle input into MCE's, your operator basically basically loses its identify as a separate operator and instead becomes  "just" a  part of the MCE operator/bundle. The only versioning that matters/survives is that of the overall MCE operator/bundle which we maintain/compute at the MCE level.

So, one approach could be when `--bundle-only` is specified, you also require a `--commit` and then just plug in a dummy x.y in `spec.version` and in `spec.name`, and use that dummy x.y if you need an x.y to compute a channel name, etc.   No need for us to give you a `--version-base` to use as we're just going ignore all of the places it would it would be used in.

Is something like this reasonable for your to implement?

**Comment by abutcher** [comment]
Tested with several commit-ish parameters with one bogus one. Changes look good to me as long as they work for @joeg-pro 
/lgtm

```
➜  hive (HIVE-1954/bundle-gen-bundle-only) ✔ ./hack/bundle-gen.py --dummy-bundle 74831db
Cloning git@github.com:openshift/hive.git to /tmp/hive-repo-hgzflia7
Working in /tmp/hive-repo-hgzflia7
Checking out 74831db3a27301cc195ef4e78a43ebab36b10e9c
Skipping build of container quay.io/openshift-hive/hive:v0.0.3227-74831db
Writing bundle files to directory: /tmp/hive-operator-bundle-qiij5rek
Generating CSV for version: 0.0.3227-74831db 
Wrote ClusterServiceVersion: /tmp/hive-operator-bundle-qiij5rek/0.0.3227-74831db/hive-operator.v0.0.3227-74831db.clusterserviceversion.yaml
Wrote bundle to /home/abutcher/go/src/github.com/openshift/hive/hive-operator-bundle-0.0.3227-74831db
```

```
./hack/bundle-gen.py --dummy-bundle origin/ocm-2.5-mce-2.0
Cloning git@github.com:openshift/hive.git to /tmp/hive-repo-258_swi8
Working in /tmp/hive-repo-258_swi8
Checking out a2ed9b3b59e7a3b5ae75ca8106c3d120f6932829
Skipping build of container quay.io/openshift-hive/hive:v0.0.3516-a2ed9b3
Writing bundle files to directory: /tmp/hive-operator-bundle-e4jaeiao
Generating CSV for version: 0.0.3516-a2ed9b3
Wrote ClusterServiceVersion: /tmp/hive-operator-bundle-e4jaeiao/0.0.3516-a2ed9b3/hive-operator.v0.0.3516-a2ed9b3.clusterserviceversion.yaml
Wrote bundle to /home/abutcher/go/src/github.com/openshift/hive/hive-operator-bundle-0.0.3516-a2ed9b3
```

```
➜  hive (HIVE-1954/bundle-gen-bundle-only) ✗ ./hack/bundle-gen.py --dummy-bundle beans
Cloning git@github.com:openshift/hive.git to /tmp/hive-repo-ut59ulmq
Traceback (most recent call last):
  File "/home/abutcher/go/src/github.com/openshift/hive/./hack/bundle-gen.py", line 495, in <module>
    hive_commit = hive_repo.rev_parse(args.dummy_bundle).hexsha
  File "/home/abutcher/.local/lib/python3.10/site-packages/git/repo/fun.py", line 357, in rev_parse
    obj = cast(Commit_ish, name_to_object(repo, rev))
  File "/home/abutcher/.local/lib/python3.10/site-packages/git/repo/fun.py", line 163, in name_to_object
    raise BadName(name)
gitdb.exc.BadName: Ref 'beans' did not resolve to an object
```

**Comment by joeg-pro** [comment]
@2uasimojo Thanks for the updates.  Just did a quick test and it works as expected.

/lgtm

**Comment by 2uasimojo** [comment]
Thanks @joeg-pro 

/hold cancel

**Pull request merged**
