### PR TITLE
Fix missing details in Azure install-config and CD.Spec.

### PR DESCRIPTION
**Pull request by dgoodwin**

### CODE REVIEW

**Comment by dgoodwin** [comment]
Just waiting on a successful azure deploy but it's at 99% and looking good.

**Comment by dgoodwin** [comment]
Hmm where's our CI...

**Comment by staebler** [comment]
This looks good. I'll wait for e2e-azure test to compete before giving a lgtm.

**Comment by staebler** [comment]
The e2e failure is from the changes that @joelddiaz made for SSH private key secret. https://github.com/openshift/hive/pull/686

**Pull request merged**
