### PR TITLE
add install log regexp for bootstrap failed

### PR DESCRIPTION
**Pull request by gregsheremeta**
/assign @joelddiaz 
/assign @2uasimojo

### CODE REVIEW

**Review by joelddiaz — COMMENTED** [review]
IIUC, the regex matching happens top-to-bottom. This seems like a very generic error as bootstrap can fail for any number of reasons. Should this be near the bottom of the regex list, or am I missing the bigger picture on how the regex handling works?

**Comment by gregsheremeta** [comment]
Where it's placed now should be good. I wanted it to come after all the cloud-specific things, but before all the other general and fallback problems. All of the other items in the `Generic OpenShift Install` section can only happen post bootstrap succeeding.

**Review by 2uasimojo — COMMENTED** [review]
/lgtm

**Review by 2uasimojo — COMMENTED** [review]
/lgtm

**Pull request merged**
