### PR TITLE
Formatting changes from "make fmt" on go version 1.11.6

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

### CODE REVIEW

**Comment by dgoodwin** [comment]
Yeah looks like the test environment is still setup to use go 1.11. Not sure if this is one of the Dockerfiles in our repo or something referenced in our config in openshift/release. I'd probably start in openshift/release.

**Comment by LalatenduMohanty** [comment]
>  Not sure if this is one of the Dockerfiles in our repo or something referenced in our config in openshift/release. I'd probably start in openshift/release.

I am trying to figure it out.

**Comment by dgoodwin** [comment]
/override ci/prow/unit
/override ci/prow/e2e

Force merging because we're running out of memory, we can't merge the release PR because of these formatting errors, and we can't merge this because the unit tests won't pass.

**Pull request merged**
