### PR TITLE
Add install log regex for GCPQuotaSSDTotalGBExceeded.

### PR DESCRIPTION
**Pull request by dgoodwin**
/assign @akhil-rane

### CODE REVIEW

**Review by akhil-rane — COMMENTED** [review]
/lgtm

**Comment by suhanime** [comment]
/hold

Until merge conflict has been resolved

**Comment by dgoodwin** [comment]
Sorry @akhil-rane needs another look. Rebased on master now.

**Review by akhil-rane — COMMENTED** [review]
/lgtm

**Pull request merged**
