### PR TITLE
restore behavior that disables velero by default

### PR DESCRIPTION
**Pull request by joelddiaz**
...unless explicitly enabled

### CODE REVIEW

**Comment by joelddiaz** [comment]
the question here is whether the Hive operator should use the ability to disable controllers (introduced in the PR that broke velero originally)
/hold

**Comment by dgoodwin** [comment]
I don't see any reason why the operator can't configure the running controllers by that method (the CLI args I assume?), however we do have established precedent of configuring via env vars like this, so for consistency I'd probably stick with what you have here and we do everywhere else.

This looks good to me, over to @twiest  for approval though.

**Comment by joelddiaz** [comment]
@twiest PTAL

**Pull request merged**
