### PR TITLE
update vendoring of x/crypto

### PR DESCRIPTION
**Pull request by joelddiaz**

### CODE REVIEW

**Comment by 2uasimojo** [comment]
Vendor changes only. If CI is happy, I'm happy.

/lgtm

**Comment by ldpliu** [comment]
@joelddiaz please help to cherry-pick this fix to ocm-2.4 and ocm-2.3 branch
Thank you

**Comment by 2uasimojo** [comment]
Given the nature of the conflicts, it probably makes more sense just to redo the changes rather than trying to cherry-pick.

**Comment by 2uasimojo** [comment]
Let's see if these work.
- ocm-2.4: #1654
- ocm-2.3: #1655

**Pull request merged**
