### PR TITLE
December Revendor

### PR DESCRIPTION
**Pull request by dlom**
xref: https://issues.redhat.com/browse/HIVE-2004

Commits have been broken out into logical chunks for easier review

### CODE REVIEW

**Comment by 2uasimojo** [comment]
/retest

timeout flake

**Comment by abutcher** [comment]
`e2e-azure` failure is probably real https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_hive/1928/pull-ci-openshift-hive-master-e2e-azure/1601228610981597184/artifacts/e2e-azure/test/artifacts/hive_machinepools.yaml

**Comment by 2uasimojo** [comment]
lgtm. @abutcher for the final stamp.

**Comment by dlom** [comment]
nevermind I guess

**Pull request merged**
